### ISSUE TITLE
Use io.elementary.Platform rather than .Sdk

### ISSUE THREAD

**Issue by hanaral** [hezral/stashed#1]
I'm not sure whether this is just a mistake or not but the idea is to just use the runtime unless you have a good reason to due to its size. elementary Code is the only app I know that actually uses the Sdk as the runtime because it needs some specific libs and it's already a developer IDE.

**Comment by hezral** [comment]
thanks, i'm building on a raspberry pi build of Odin, and currently it doesn't have the elementary flatpak-platform yet so i build locally. will change it to the proper runtime once its ready for AppCenter :)

**Comment by hezral** [comment]
keeping this open, when its ready
