### ISSUE TITLE
Incorrect appstream install location

### ISSUE THREAD

**Issue by danirabbit** [hezral/stashed#4]
https://github.com/hezral/stashed/blob/2cb01fbe03130425cce56b1c671c9d762c42c37d/data/meson.build#L24

Same issue as https://github.com/hezral/keystrokes/issues/1

While trying to review your app, Sideload seems to be stuck on not being able to load appdata. I noticed you're installing to `share/appdata` which is a very old location. This file should instead be installed to `share/metainfo`

**Comment by hezral** [comment]
Thanks, i've updated it now. I was using Builder to generate a skeleton project directory, i think it came from there.
