### ISSUE TITLE
Invalid screenshot URL

### ISSUE THREAD

**Issue by danirabbit** [hezral/stashed#5]
https://github.com/hezral/stashed/blob/fd0b3ec848a870745edff7944b2c2dd5fb70504c/data/com.github.hezral.stashed.appdata.xml.in#L30

It looks like you probably changed from `master` to `main` so this is redirecting to a non-"raw" location. FWIW, the query param from "raw" redirects to `https://raw.githubusercontent.com/hezral/stashed/main/data/screenshot-01.png` so it might be slightly faster to just use the `raw.githubusercontent.com` url

**Comment by hezral** [comment]
thanks, didn't know that
