### ISSUE TITLE
Brand colors in AppData don't pass contrast check

### ISSUE THREAD

**Issue by danirabbit** [hezral/stashed#6]
https://github.com/hezral/stashed/blob/fd0b3ec848a870745edff7944b2c2dd5fb70504c/data/com.github.hezral.stashed.appdata.xml.in#L75

It looks like these colors have a contrast ratio of only 1.9:1, but 3:1 is required as a minimum. See:

![Screenshot from 2021-11-04 16 27 24](https://user-images.githubusercontent.com/7277719/140433962-6e1d6e6f-946b-490d-81ce-6cd6d7443fee.png)

We really recommend that folks try to hit WCAG AA level contrast which is 4.5:1.

To do this with a light foreground color, your foreground color would have to be `#fff` and your background color could be something like `#CC4E00`:

![Screenshot from 2021-11-04 16 31 15](https://user-images.githubusercontent.com/7277719/140434251-7e0ba844-5649-4471-a3e3-20e6cf43221c.png)

Or going the other way it could be a foreground of `#662200` and keep the same background like:

![Screenshot from 2021-11-04 16 33 29](https://user-images.githubusercontent.com/7277719/140434428-80e27a56-3d2c-4ea9-bd30-015071c5404e.png)

**Comment by hezral** [comment]
thanks, i like the last option :) will make the change
