### ISSUE TITLE
Remove home Filesystem permission

### ISSUE THREAD

**Issue by danirabbit** [hezral/stashed#7]
I can't see any feature of your app that require permissions for all of `home`. Can you explain that?

While we're modifying permissions, you no longer need access to `accountsservice` since there's a portal for that

**Comment by hezral** [comment]
Stashed acts like a box where you drop files for later when you want to copy it. 
I think home permission is necessary, as thats where a user file lives. 
Without the permission, the app can't read the file URIs when a file is drag n drop to it. 

got it on the accountservices

**Comment by danirabbit** [comment]
@hezral building your app here without the home permission seems to work as far as I can tell. Drag and drop should use a portal to grant access to dropped files

**Comment by danirabbit** [comment]
Nevermind, this isn't correct. the file transfer portal only works for GTK3

**Comment by hezral** [comment]
You mean gtk4 right? I was reading into it too just now

**Comment by danirabbit** [comment]
Ah yeah sorry that's what I meant! my bad
